version: "3.8"
name: minio-s3
services:
  s3:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data
  createbuckets:
    image: minio/mc
    depends_on:
      - s3
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add s3 http://s3:9000 admin password;
      /usr/bin/mc mb s3/local-bucket;
      /usr/bin/mc policy download s3/local-bucket;
      /usr/bin/mc version enable s3/local-bucket;
      exit 0;"
