version: "3.8"

name: "mongodb"
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest

    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password

    ports:
      - 27017:27017

    volumes:
      - mongodb_data:/var/lib/mongodb/data

volumes:
  mongodb_data:
