version: "3.8"

name: postgres
services:
  db:
    container_name: postgres
    image: postgres

    environment:
      POSTGRES_DB: DB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

    ports:
      - 5432:5432

    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
